source 'https://cdn.cocoapods.org/'

# ignore all warnings from all pods
inhibit_all_warnings!

platform :ios, '14.1'

workspace 'ios-app.xcworkspace'
project 'ios-app',
  'dev-release' => :release, 'stage-release' => :release,
  'dev-debug' => :debug, 'stage-debug' => :debug,
  'prod-debug' => :debug, 'prod-release' => :release

use_frameworks!

def design_pod
 pod 'design', :path => 'DevPods/design'
end

def authorization_pod
  pod 'authorization', :path => 'DevPods/authorization'
end

def common_pod
  pod 'common', :path => 'DevPods/common'
end

def registration_pod
  pod 'registration', :path => 'DevPods/registration'
end

def otp_pod
  pod 'otp', :path => 'DevPods/otp'
end

def biometric_pod
  pod 'biometric', :path => 'DevPods/biometric'
end

def dev_pods
  design_pod
  common_pod
  authorization_pod
  registration_pod
  otp_pod
  biometric_pod
end

# workaround for https://github.com/CocoaPods/CocoaPods/issues/8073
# need for correct invalidate of cache MultiPlatformLibrary.framework
install! 'cocoapods', :disable_input_output_paths => true

pre_install do |installer|
  # CocoaPods needs access to such frameworks during installation process to obtain
  # their type (static or dynamic) and configure the Xcode project accordingly.
  # Build MultiPlatformLibrary framework to correct install Pod
  puts "prepare MultiPlatformLibrary.framework (require some time...)"
  `cd .. && ./gradlew :mpp-library:syncMultiPlatformLibraryDebugFrameworkIosX64`
  puts "preparing MultiPlatformLibrary.framework complete"
end

target 'ios-app' do
  dev_pods
  pod 'MultiPlatformLibrary', :path => '../mpp-library'
#  pod 'MultiPlatformLibraryUnits/Core',
#    :git => 'https://github.com/icerockdev/moko-units.git', :tag => 'release/0.7.0'
  pod 'MCRCDynamicProxy',
    :git => 'https://github.com/icerockdev/moko-crash-reporting.git', :tag => 'release/0.2.1'
  pod 'MCRCStaticReporter',
    :git => 'https://github.com/icerockdev/moko-crash-reporting.git', :tag => 'release/0.2.1'

  pod 'SwiftFormat/CLI', '~> 0.49.4'   # Install swift-format command line tool, can be called for autoformat or lint
  
  # https://github.com/ninjaprox/NVActivityIndicatorView - множество вариантов отображения загрузки с удобным API
  # pod 'NVActivityIndicatorView', '~> 5.1.1'
  
  # pod 'Firebase', '~> 6.33.0'
  # pod 'R.swift', '~> 5.3.1'           # Code generation for resources  https://github.com/mac-cain13/R.swift
  # pod 'ProgressHUD', '~> 2.70'        # Loading animation https://github.com/relatedcode/ProgressHUD
  # pod 'Toast-Swift', '~> 5.0.1'       # Showing toasts https://github.com/scalessec/Toast-Swift
  # pod 'XLPagerTabStrip', '~> 9.0'     # Tabs controller like an Android PagerTabStrip
  # pod 'AlamofireImage', '~> 3.6.0'    # Image loader with cache https://github.com/Alamofire/AlamofireImage
  # pod 'Down', '~> 0.10.0'             # Markdown rendering https://github.com/johnxnguyen/Down
  # pod 'RxKeyboard', '~> 1.0.0'        # Reactive way of observing keyboard frame changes https://github.com/RxSwiftCommunity/RxKeyboard
  # pod 'SwiftLint', '~> 0.40.3'        # A tool to enforce Swift style and conventions. https://github.com/realm/SwiftLint
  # pod 'DatePickerDialog', '~> 4.0'    # Date picker dialog (based on UIDatePicker) https://github.com/squimer/DatePickerDialog-iOS-Swift
  # pod "AlignedCollectionViewFlowLayout", '~> 1.1.2' # Collection view layout with custom align https://github.com/mischa-hildebrand/AlignedCollectionViewFlowLayout
  # pod 'InfiniteLayout', :git => 'https://github.com/icerockdev/InfiniteLayout', :branch => 'master' # Infinite collection view layout
  # pod 'SSZipArchive', '~> 2.4.2'      # Zip format support
  # pod 'AssetImportKit', '~> 1.1.1'    # Import 3D model dynamically on SceneKit
end

target 'design_Example' do
  use_frameworks!
  project 'DevPods/design/Example/design.xcodeproj'

  design_pod
end

target 'authorization_Example' do
  use_frameworks!
  project 'DevPods/authorization/Example/authorization.xcodeproj'

  authorization_pod
end

target 'common_Example' do
  use_frameworks!
  project 'DevPods/common/Example/common.xcodeproj'

  design_pod
  common_pod
end

target 'registration_Example' do
  use_frameworks!
  project 'DevPods/registration/Example/registration.xcodeproj'
  
  registration_pod
  design_pod
end

target 'otp_Example' do
  use_frameworks!
  project 'DevPods/otp/Example/otp.xcodeproj'
  
  otp_pod
  design_pod
  biometric_pod
end

target 'biometric_Example' do
  use_frameworks!
  project 'DevPods/biometric/Example/biometric.xcodeproj'

  biometric_pod
  design_pod
end
